// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIazOyaWFGu2Gjb-JEzhiE3SLrjnn5cnE',
    appId: '1:563944314344:web:ac2e991d5ce4701877c05d',
    messagingSenderId: '563944314344',
    projectId: 'red-social-api',
    authDomain: 'red-social-api.firebaseapp.com',
    storageBucket: 'red-social-api.appspot.com',
    measurementId: 'G-EETTT90FCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP61ARRMnxdVMXNswsA9hDbkmRJeHH6EM',
    appId: '1:563944314344:android:705ff89c49e3f1ae77c05d',
    messagingSenderId: '563944314344',
    projectId: 'red-social-api',
    storageBucket: 'red-social-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxId58IN6BcaE2GeoXiVh3ipPffEzslkE',
    appId: '1:563944314344:ios:a1c10f0e113933cd77c05d',
    messagingSenderId: '563944314344',
    projectId: 'red-social-api',
    storageBucket: 'red-social-api.appspot.com',
    iosClientId: '563944314344-6fc5hjp3m1nrmh7ftc24h2s79qfed5ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRedSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxId58IN6BcaE2GeoXiVh3ipPffEzslkE',
    appId: '1:563944314344:ios:a1c10f0e113933cd77c05d',
    messagingSenderId: '563944314344',
    projectId: 'red-social-api',
    storageBucket: 'red-social-api.appspot.com',
    iosClientId: '563944314344-6fc5hjp3m1nrmh7ftc24h2s79qfed5ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRedSocial',
  );
}
